config/routes.rb
Rails.application.routes.draw do
  resources :services
  devise_for :users
  resources :testimonials
  resources :home_page
  
  root 'home_page#index'

  get 'testimonials' => 'testimonials#index'

  get 'contact_us' => 'home_page#contact_us'

  get 'services' => 'services#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.admin?
        can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home_page.rb
class HomePage < ApplicationRecord
	mount_uploaders :pictures, PicturesUploader
	serialize :pictures, JSON
end

app/models/service.rb
class Service < ApplicationRecord
	mount_uploaders :pictures, PicturesUploader
	serialize :pictures, JSON
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
  	role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
	before_action :set_home_page, only: [:index, :contact_us, :edit, :update, :destroy]
  def index
  end

  def contact_us
  end

  def new
  	@home_page = HomePage.new
  end

  def edit
  	
  end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_home_page
	  @home_page = HomePage.first
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def home_page_params
	  params.require(:home_page).permit({pictures:[]})
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :info, {pictures:[]})
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:content, :user_id, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/home_page/_form.html.erb
<%= form_with(model: home_page, local: true) do |form| %>
  <% if home_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home_page.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% home_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, id: :post_pictures, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home_page/contact_us.html.erb
<h1 class="text-center">Contact Us</h1>

<br><br>

<div class="container">
	<p class="text-center">Here at GroundUp we're ready to help you with all of your remodeling needs.<br> If you would like more information on what we can do for you, please fill out the form <br> below and we will have one of our service specialists contact you.</p>
</div>

<br><br>

<div class="row">
	<div class="col-md-1">
		<ul class="nav nav-pills nav-stacked">
		  <li><a href="https://twitter.com/" target="_blank" class="btn btn-lg btn-social-icon btn-twitter btn-color"><span class="fa fa-twitter" style="font-size:36px"></span></a></li>
		  <li><a href="https://www.facebook.com/" target="_blank" class="btn btn-lg btn-social-icon btn-facebook btn-color"><span class="fa fa-facebook" style="font-size:36px"></span></a></li>
		  <li><a href="https://www.instagram.com/" target="_blank" class="btn btn-lg btn-social-icon btn-instagram btn-color"><span class="fa fa-instagram" style="font-size:36px"></span></a></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="text-center">
			<form action="/action_page.php">
				First name:
				<input type="text" name="firstname"><br><br>
				Last name:
	  			<input type="text" name="lastname"><br><br>
	  			Your Email:
	  			<input type="text" name="email"><br><br>
	  			<input class="btn btn-primary" type="submit" value="Submit">
			</form>
		</div>
	</div>
</div>

app/views/home_page/edit.html.erb
<h1>New Image</h1>

<%= render 'form', home_page: @home_page %>

<%= link_to 'Back', root_path %>

app/views/home_page/index.html.erb
<h1 class="text-center">Welcome to GroundUp</h1>


<div class="row">
	<div class="col-md-12 text-center">
			<h3>Are You Planning To Renovate Your Home or Business?</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12 text-center">
			<p>Send Us An Email To Schedule An Appointment With Our Very Own Experts For Your Personal Or Commercial Remodeling Needs.</p>
	</div>
</div>

app/views/home_page/new.html.erb
<h1>New Image</h1>

<%= render 'form', home_page: @home_page %>

<%= link_to 'Back', root_path %>

app/views/homepage/contact_us.html.erb
<h1 class="text-center">Contact Us</h1>

<br><br>

<p class="text-center">Here at GroundUp we're ready to help you with all of your remodeling needs. If you would like more information on what we can do for you, please fill out the form below and we will have one of our service specialists contact you.</p>

<br><br>

<div class="row">
	<div class="col-md-1">
		<ul class="nav nav-pills nav-stacked">
		  <li><a href="https://twitter.com/" target="_blank" class="btn btn-lg btn-social-icon btn-twitter btn-color"><span class="fa fa-twitter" style="font-size:36px"></span></a></li>
		  <li><a href="https://www.facebook.com/" target="_blank" class="btn btn-lg btn-social-icon btn-facebook btn-color"><span class="fa fa-facebook" style="font-size:36px"></span></a></li>
		  <li><a href="https://www.instagram.com/" target="_blank" class="btn btn-lg btn-social-icon btn-instagram btn-color"><span class="fa fa-instagram" style="font-size:36px"></span></a></li>
		</ul>
	</div>

	<div class="col-md-10">
		<div class="text-center">
			<form action="/action_page.php">
				First name:
				<input type="text" name="firstname"><br><br>
				Last name:
	  			<input type="text" name="lastname"><br><br>
	  			Your Email:
	  			<input type="text" name="email"><br><br>
	  			<input class="btn btn-primary" type="submit" value="Submit">
			</form>
		</div>
	</div>
</div>

app/views/homepage/index.html.erb
<h1 class="text-center">Welcome to GroundUp</h1>

<div class="row">
	<div class="col-md-12 text-center">
			<h3>Are You Planning To Renovate Your Home or Business?</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12 text-center">
			<p>Send Us An Email To Schedule An Appointment With Our Very Own Experts For Your Personal Or Commercial Remodeling Needs.</p>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Testimonials", testimonials_path %></li>
        <li><%= link_to "Services", services_path %></li>
<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
          <ul class="dropdown-menu">
          </ul>
        </li> -->
      </ul>

      <!-- end of left side, starting right side -->

      <!-- for the shopping cart glyphicon -->
      <!-- <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> -->

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact Us", contact_us_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroundUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render 'layouts/navbar' %>

  	<div class="container">
    	<%= yield %>
	</div>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :service_name %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info, id: :service_info %>
  </div>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, id: :post_pictures, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
 <p id="notice"><%= notice %></p>

<h1 class="text-center">Our Services</h1>

<br><br>


  <div class="row">
    <% @services.each_with_index do |service| %>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-10">
            <h2><%= service.name %></h2>
              <p><%= service.info %></p>
          </div>
          <div class="col-md-2">
            <% service.pictures.each do |pic| %>
              <p><%= image_tag pic.url, class: "service-pic" %></p>
            <% end %>
          </div>
        </div>
      </div>
  <!--           Make this so that only admins can see and use -->
        <% if current_user && (can? :update, @service) %>
          <p><%= link_to 'Show', service %></p>
          <p><%= link_to 'Edit', edit_service_path(service) %></p>
          <p><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
    <% end %>
    <% if current_user && (can? :create, @service) %>
      <%= link_to "New Service", new_service_path %>
    <% end %>
  </div>
<br />

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @service.info %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  	<% @service.pictures.each_with_index do |pic, index| %>
	  	<% if index == 0 %>
	    	<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	    <% else %>
	    	<li data-target="#carousel-example-generic" data-slide-to="<%= index %>"></li>
	    <% end %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<% @service.pictures.each_with_index do |pic, index| %>
  	<% if index == 0 %>
    	<div class="item active">
    <% else %>
    	<div class="item">
    <% end %>

      <%= image_tag pic.url %>
    	</div>
    <% end %>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/testimonials/_form.html.erb
<%= form_with(model: testimonial, local: true) do |form| %>
  <% if testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :testimonial_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :testimonial_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form', testimonial: @testimonial %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.content %></td>
        <td><%= testimonial.user_id %></td>
        <% if current_user && testimonial.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
          <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form', testimonial: @testimonial %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @testimonial.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @testimonial.user_id %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>